#!/bin/bash

## #ddev-generated
## Description: Run Experience Builder's Cypress tests headlessly.
## Usage: xb-cypress-run
## Example: ddev xb-cypress-run                     Run all tests.\nddev xb-cypress-run --env "VAR=value"   Pass arbitrary command arguments.
## Aliases: cy-run,cy:run
## OSTypes: darwin
## ExecRaw: true

cd "$(dirname "$0")" || exit; source .xb-command-include

# Run Cypress.
ddev exec \
  --dir /var/www/html/web/modules/contrib/experience_builder/ui \
  "node_modules/.bin/cypress run --browser electron " . "$@"
