#!/bin/bash

## #ddev-generated
## Description: Run Cypress tests headlessly.
## Usage: xb-cypress-run
## Example: ddev xb-cypress-run                     Run all tests.\nddev xb-cypress-run --env "VAR=value"   Pass arbitrary command arguments.
## Aliases: cy-run,cy:run
## OSTypes: darwin
## ExecRaw: true

cd "$(dirname "$0")" || exit; source .xb-command-include

xb_cypress "run --browser electron $*"
