#!/bin/bash

## #ddev-generated
## Description: Run Experience Builder's Cypress component/unit tests.
## Usage: xb-cypress-component
## Example: ddev xb-cypress-component                     Run all tests.\nddev xb-cypress-component --env "VAR=value"   Pass arbitrary command arguments.
## Aliases: cy-component,cy:component
## OSTypes: darwin
## ExecRaw: true

cd "$(dirname "$0")" || exit; source .xb-command-include

# Run Cypress.
ddev exec \
  --dir /var/www/html/web/modules/contrib/experience_builder/ui \
  "node_modules/.bin/cypress run --component " . "$@"
