#!/bin/bash

## #ddev-generated
## Description: Clean-install Experience Builder's UI app.
## Example: ddev xb-npm-ci
## Aliases: npm-ci,npm:ci

cd "$(dirname "$0")" || exit 1; source .xb-command-include || exit 1

npm ci
