#!/bin/bash

## #ddev-generated
## Description: Set up the Experience Builder development environment.
## Usage: xb-setup
## Example: ddev xb-setup\nddev xb-setup --force
## Flags: [{"Name":"force","Shorthand":"f","Usage":"Completely reset an existing environment if present and start over"}]
## ExecRaw: true

cd "$(dirname "$0")" || exit
cd ../../../
set -e

# Route Composer commands through DDEV.
alias composer="ddev composer"

# Flag-handling.
while :; do
  case ${1:-} in
    -f | --force)
      FORCE=true ;;
    --)
      shift
      break ;;
    -?*)
      printf 'WARN: Unknown option (ignored): %s\n' "$1" >&2 ;;
    *) # Default case: No more options, so break out of the loop.
      break ;;
  esac
  shift
done

# Exit early if the environment is already set up.
if [ -d web/modules/contrib/experience_builder/.git ] && [ ! "$FORCE" ]; then
  GREEN="\033[0;32m"
  NO_COLOR="\033[0m"
  printf "%bThe Experience Builder development environment is already set up.%b\n" "$GREEN" "$NO_COLOR"
  # shellcheck disable=SC2016
  echo 'Note: If the environment is broken, run `ddev xb-setup --force` to completely reset it and start over.'
  echo 'Warning: If you do this, you will lose any changes you have made to the Experience Builder module or your Drupal site. Back up anything you want to save.'
  echo Hint: ddev xb-setup --force
  exit
fi

# Remove the Experience Builder module if it's there.
rm -rf web/modules/contrib/experience_builder
mkdir -p web/modules/contrib

# Place the Experience Builder module via Git for development. Require
# it with Composer to test its composer.json and place dependencies.
git clone \
  git@git.drupal.org:project/experience_builder.git \
  web/modules/contrib/experience_builder

# Allow all Composer plugins.
composer config \
  --no-plugins \
  allow-plugins.\* \
  true

# Require Drush, but don't install yet for performance reasons.
composer require \
  --no-install \
  --update-with-all-dependencies \
  --no-interaction \
  drush/drush

# Require the Experience Builder module. Still don't install.
composer config \
  repositories.xb \
  path \
  web/modules/contrib/experience_builder
composer require \
  --no-install \
  --update-with-all-dependencies \
  --no-interaction \
  drupal/experience_builder

# Require dev dependencies. NOW install.
composer require \
  --dev \
  --update-with-all-dependencies \
  --no-interaction \
  devizzent/cebe-php-openapi:^1.0.3 \
  drupal/metatag:^2. \
  jangregor/phpstan-prophecy:^1.0.2 \
  league/openapi-psr7-validator:^0.22.0 \
  webflo/drupal-finder:^1.3.1

# Allow test modules and themes to be installed.
# shellcheck disable=SC2016
printf '\n# Allow test modules and themes to be installed.\n$settings["extension_discovery_scan_tests"] = TRUE;' \
  >> web/sites/default/settings.ddev.php

# Install Drupal and enable the Experience Builder module.
ddev xb-site-install

# Install Drupal core NPM packages.
ddev exec --dir /var/www/html/web/core -- npm install

# Build front-end assets.
ddev xb-ui-build

# Install DDEV Selenium Standalone Chrome
ddev add-on get ddev/ddev-selenium-standalone-chrome
