#ddev-generated
web_environment:
  - BASE_URL=http://web
  - CYPRESS_CACHE_FOLDER=/var/www/html/.cache/cypress
  - DB_URL=sqlite://web/sites/default/files/db.sqlite
  - DISPLAY=host.docker.internal:0
  - DRUPAL_TEST_DB_URL=sqlite://web/sites/default/files/db.sqlite
  - VITE_SERVER_ORIGIN=https://${DDEV_HOSTNAME}:5174
webimage_extra_packages:
  - libasound2
  - libgbm-dev
  - libgtk-3-0
  - libgtk2.0-0
  - libnotify-dev
  - libnss3
  - libxss1
  - libxtst6
  - xauth
  - xvfb
web_extra_exposed_ports:
  - name: vite-dev-server
    container_port: 5173
    http_port: 5173
    https_port: 5174
