#!/bin/bash

## #ddev-generated
## Description: Run Experience Builder's Cypress tests.
## Usage: cypress [spec-pattern]
## Example: ddev cypress                       Run all tests.\nddev cypress "e2e/*.cy.js"         Run all end-to-end tests.\nddev cypress "e2e/example.cy.js"   Run a specific test.

# Run all tests by default.
SPEC_PATTERN="${1}"

# if [ "${DDEV_PROJECT_STATUS}" != "running" ] && [ -z "$no_recursion" ]; then
#   echo "Project ${DDEV_PROJECT} is not running. Starting it..."
#   ddev start
#   start_exit_code=$?
#   if [ $start_exit_code -ne 0 ]; then
#     exit $start_exit_code
#   fi
#   # Run again since the environment is updated after `ddev start`.
#   no_recursion=true ddev "$(basename "$0")" "$@"
#   exit $?
# fi

cd /var/www/html/web/modules/contrib/experience_builder/ui || exit
node_modules/.bin/cypress run \
  --browser electron \
  --spec "../tests/src/Cypress/cypress/${SPEC_PATTERN}"
