#!/bin/bash

## #ddev-generated
## Description: Change the version of Drupal core.
## Usage: xb-core-set-version <core-version>
## ExecRaw: true
## Example: ddev xb-core-set-version 11.1
## Aliases: core
## Flags: []
## ExecRaw: true

cd "$DDEV_COMPOSER_ROOT" || exit 1

composer require --no-update --dev drupal/core-dev:^$*
composer require --no-update drupal/core-recommended:^$* drupal/core-composer-scaffold:^$* drupal/core-project-message:^$*
composer update --with-all-dependencies
