#!/bin/bash

## #ddev-generated
## Description: Add some convenience extras for development.
## Usage: xb-dev-extras
## Example: ddev xb-dev-extras\nddev xb-dev-extras --dry-run
## Aliases: extras
## Flags: [{"Name":"dry-run","Usage":"Show what the command will do if run"}]

#  If the '--dry-run' flag is passed, show what the command would do and then exit.
if [[ "$1" == "--dry-run" ]]; then
  echo "This command will...
  1. Install the following modules:
     - Admin Toolbar (admin_toolbar)
     - Admin Toolbar (admin_toolbar_tools)
     - Coffee (coffee)
  2. Create a test page at '/test'."
  exit 0
fi

# Add the modules to the codebase.
composer require \
  --no-interaction \
  drupal/admin_toolbar \
  drupal/admin_toolbar_tools \
  drupal/coffee

# Install the modules in Drupal.
drush en -y \
  admin_toolbar \
  admin_toolbar_tools \
  coffee


