#!/bin/bash

## #ddev-generated
## Description: Find problems in JavaScript code with ESLint.
## Example: ddev xb-eslint
## Aliases: eslint

cd "$DDEV_COMPOSER_ROOT/$DDEV_DOCROOT/modules/contrib/experience_builder/ui" || exit 1

npm run lint:eslint
