#!/bin/bash

## #ddev-generated
## Description: Clean-install Experience Builder's UI app.
## Example: ddev xb-npm-ci
## Aliases: npm-ci,npm:ci

cd "$DDEV_COMPOSER_ROOT/$DDEV_DOCROOT/modules/contrib/experience_builder/ui" || exit 1

npm ci
