#!/bin/bash

## #ddev-generated
## Description: Automatically fix standards violations where possible with PHPCBF.
## Example: ddev xb-phpcbf
## Aliases: phpcbf,cbf,fix

cd "$DDEV_COMPOSER_ROOT/$DDEV_DOCROOT" || exit 1

../vendor/bin/phpcbf \
  -s \
  --standard=modules/contrib/experience_builder/phpcs.xml \
  --basepath=modules/contrib/experience_builder \
  modules/contrib/experience_builder
