#!/bin/bash

## #ddev-generated
## Description: Change the version of Drupal core.
## Example: ddev xb-set-core-version 11.1

cd "$DDEV_COMPOSER_ROOT" || exit 1

composer require --no-update --dev drupal/core-dev:^$*
composer require --no-update drupal/core-recommended:^$* drupal/core-composer-scaffold:^$* drupal/core-project-message:^$*
composer update --with-all-dependencies
