#!/bin/bash

## #ddev-generated
## Description: (Re)install Drupal and the Experience Builder module.
## Example: ddev xb-site-install
## Aliases: site-install,si

# Install Drupal.
drush site:install -y \
  --account-name=admin \
  --account-pass=admin \
  --site-name="XB Local Dev"

# Enable the Experience Builder module.
drush pm:install -y \
  experience_builder \
  xb_dev_standard

# Create a default article.
drush php:eval "(\Drupal\node\Entity\Node::create(['type' => 'article', 'title' => 'Test', 'uid' => 1]))->save();"

# Display a one time login link for user ID 1.
drush uli
