#!/bin/bash

## #ddev-generated
## Description: Automatically fix Stylelint errors where possible.
## Example: ddev xb-stylelint-fix
## Aliases: stylelint-fix,stylelint:fix,css-fix,css:fix

UI_DIR="$DDEV_COMPOSER_ROOT/$DDEV_DOCROOT/modules/contrib/experience_builder/ui"
cd "$UI_DIR" || exit 1

npx stylelint \
  --config "$DDEV_COMPOSER_ROOT/$DDEV_DOCROOT/core/.stylelintrc.json" \
  --ignore-pattern "dist/**/*" \
  "$UI_DIR/**/*.css" \
  --fix
