#!/bin/bash

## #ddev-generated
## Description: (Re)install Drupal and the Experience Builder module.
## Example: ddev xb-site-install
## Aliases: site-install,si

# Install Drupal.
drush site:install -y \
  --account-name=admin \
  --account-pass=admin \
  --site-name="XB Local Dev"

# Enable Experience Builder and development modules if present.
modules=(experience_builder)
XB_DEV_STANDARD="xb_dev_standard"
# As of now, the xb_dev_standard should always be there, but in the event that
# it gets removed or renamed, this check will prevent an error.
if drush pm:list --type=Module --status=disabled | grep -q "^$XB_DEV_STANDARD$"; then
  modules+=("$XB_DEV_STANDARD")
fi
drush pm:install -y "${modules[@]}"

# Create a default article.
drush php:eval "(\Drupal\node\Entity\Node::create(['type' => 'article', 'title' => 'Test', 'uid' => 1]))->save();"

# Display a one time login link for user ID 1.
drush uli
