#!/bin/bash

## #ddev-generated
## Description: Find errors and enforce conventions with Stylelint.
## Example: ddev xb-stylelint
## Aliases: stylelint,css

UI_DIR="$DDEV_COMPOSER_ROOT/$DDEV_DOCROOT/modules/contrib/experience_builder/ui"
cd "$UI_DIR" || exit 1

npx stylelint \
  --config "$DDEV_COMPOSER_ROOT/$DDEV_DOCROOT/core/.stylelintrc.json" \
  --ignore-pattern "dist/**/*" \
  "$UI_DIR/**/*.css"
