#!/bin/bash

## #ddev-generated
## Description: Install dependencies and run Experience Builder's UI app development server.
## Example: ddev xb-ui-dev
## Aliases: ui-dev,dev

cd "$DDEV_COMPOSER_ROOT/$DDEV_DOCROOT/modules/contrib/experience_builder/ui" || exit 1

drush pm:install xb_vite -y > /dev/null 2>&1 || :
npm install
npm run drupaldev -- --host
